# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod"];
  boot.initrd.kernelModules = ["nfs"];
  boot.initrd.supportedFilesystems = ["nfs"];
  boot.kernelModules = ["kvm-amd" "amd_iommu=on" "nvidia openvswitch"];
  boot.extraModulePackages = [];
  boot.loader.grub.useOSProber = true;
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e1b0d132-8127-4f6a-afbd-3ea7f551f070";
    fsType = "btrfs";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/771c560c-8a5a-434c-a097-4f044f2a2235";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CCA8-B5F3";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };
  fileSystems."/media" = {
    device = "/dev/disk/by-uuid/2E588FE7588FABE1";
    fsType = "ntfs";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/2ecbbe97-a7f7-4a9c-b08a-75156ab4c9c1";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp10s0u1u3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
